"""empty message

Revision ID: 7c3a8662ce5c
Revises: 923efcde0236
Create Date: 2019-08-26 20:45:42.278314

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c3a8662ce5c'
down_revision = '923efcde0236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('alias', sa.String(length=30), nullable=True),
    sa.Column('fid', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.String(length=50), nullable=True),
    sa.Column('describe', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('titlepic', sa.String(length=50), nullable=True),
    sa.Column('describe', sa.Text(), nullable=True),
    sa.Column('keywords', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.String(length=30), nullable=True),
    sa.Column('categoryid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoryid'], ['Category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.drop_index('alias', table_name='category')
    op.drop_index('name', table_name='category')
    op.drop_table('category')
    op.drop_index('title', table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('titlepic', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('describe', mysql.TEXT(), nullable=True),
    sa.Column('keywords', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('tags', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('categoryid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoryid'], ['category.id'], name='article_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('title', 'article', ['title'], unique=True)
    op.create_table('category',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('alias', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('fid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('keywords', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('describe', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'category', ['name'], unique=True)
    op.create_index('alias', 'category', ['alias'], unique=True)
    op.drop_table('Article')
    op.drop_table('Category')
    # ### end Alembic commands ###
